In [1]:
import numpy as np

In [33]:
passengers = np.arange(4)
assigned_seats = np.arange(4)
np.random.shuffle(assigned_seats)

In [ ]:
x = np.random.random(10)
print (x)
[i for i, x in enumerate(x) if x > 0.5]

In [125]:
def assign_seat(seating_chart, assigned_seat):
    open_seats = [i for i, q in enumerate(seating_chart) if q == 0]
    if assigned_seat in open_seats: seating_chart[assigned_seat] = 1
    else: 
        randomly_assigned_seat = open_seats[np.random.randint(0, len(open_seats))]
        seating_chart[randomly_assigned_seat] = 1
    return seating_chart

In [179]:
def airplane_sim(sims=100, n=10):
    lggas = 0 # last guy gets assigned seat
    for j in range(sims):
        passengers = np.arange(n)
        assigned_seats = np.arange(n)
        np.random.shuffle(assigned_seats)
        taken_seats = np.zeros(n)
        for i in passengers:
            if i == 0:
                taken_seats[np.random.randint(0, n)] = 1
            elif i == n - 1:
                if taken_seats[assigned_seats[i]] == 0: 
                    lggas += 1
            else:
                taken_seats = assign_seat(taken_seats, assigned_seats[i])
    return(lggas / sims)


0.4986


In [686]:
def airplane_sim2(n_passengers=100, n_planes=100):
    # Once someone is assigned 0, every subsequent person will then take their own seat.
    x = np.arange(n_passengers)
    y = np.repeat(x, n_planes, axis = 0)
    y = y.reshape((n_passengers, n_planes))
    y[0,:] = np.random.randint(n_passengers, size=n_planes)
    for p in range(1, n_passengers):
        q = np.where(y[:p] == p)[1]
        y[p,q] = np.random.randint(p+1, n_passengers+1, size=len(q)) % n_passengers
    lggas = y[n_passengers - 1,:].astype(bool).sum()
    return lggas / n_planes


In [554]:
def airplane_sim3(n_passengers=100):
    x = np.arange(n_passengers)
    x[0] = np.random.randint(n_passengers)
    for p in range(1, n_passengers):
        if p in x[:p]:
            x[p] = np.random.randint(p+1, n_passengers+1) % n_passengers
    lggas = x[n_passengers - 1].astype(bool).sum()
    return lggas

In [753]:
%%timeit -n1000
airplane_sim3(100)
# tot = 0
# for i in range(10000):
#     tot += airplane_sim3(100)
# tot / 10000

305 µs ± 8.98 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [533]:
n_passengers = 5
x = np.arange(n_passengers)
x[0] = np.random.randint(n_passengers)
print(x)
for p in range(1, n_passengers):
    if p in x[:p]:
        x[p] = np.random.randint(p+1, n_passengers+1) % n_passengers
x

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [555]:
%timeit airplane_sim2(100, 1000)
%timeit -n1000 airplane_sim3(100)

13.8 ms ± 210 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
291 µs ± 7.83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [218]:
x = np.arange(5)
y = np.repeat(x, 5, axis = 0)
y = y.reshape((5, y.shape[0] // 5))

In [240]:
y

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [388]:
y2 = y.copy()
y2[0,:] = np.random.randint(5, size=5)

In [383]:
y2

array([[2, 1, 4, 1, 4],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [298]:
y2[:1] == 1

array([[False, False, False, False,  True]])

In [332]:
for p in range(1, 5):
    print(p)
    print(np.where(y2[:p+1] == p+1,np.random.randint(p,6), y2[:p+1]))

1
[[0 5 4 0 1]
 [1 1 1 1 1]]
2
[[0 2 4 0 1]
 [1 1 1 1 1]
 [2 2 2 2 2]]
3
[[0 2 4 0 1]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]]
4
[[0 2 4 0 1]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [345]:
y2 = y.copy()
y2[0,:] = np.random.randint(5, size=5)
print(y2)
for p in range(1, 5):
    taken = y2[:p] == p
    assigned=np.where(taken.sum(axis=0), np.random.randint(p,5),p)
    print(assigned)
    y2[:p] = assigned

[[3 1 3 4 1]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[1 2 1 1 2]
[2 3 2 2 3]
[3 3 3 3 3]
[4 4 4 4 4]


In [365]:
y2

array([[0, 3, 4, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [391]:
p=4
y2[p,np.where(y2[:p] == p)[1]] = np.random.randint(p+1, 5)
y2

array([[2, 2, 0, 4, 4],
       [1, 1, 1, 1, 1],
       [4, 4, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [415]:
y2 = y.copy()
y2[0,:] = np.random.randint(5, size=5)
for p in range(1, 4):
    y2[p,np.where(y2[:p] == p)[1]] = np.random.randint(p+1, 6)%5
(1 - np.sum(y2[:4]==4, axis = 0)).sum()

3

In [473]:
np.where(y2[:p] == p)[1]

array([1, 2])

In [486]:
y3 = airplane_sim2(5,10)

In [487]:
y3

5

In [471]:
p=1
np.where(y3[:p] == p

array([[False,  True,  True, False, False, False, False,  True,  True,
        False]])

In [336]:
taken = y2[:1]==1
taken
taken.sum(axis=0)
np.where(taken.sum(axis=0), np.random.randint(2,5),0)

array([0, 0, 0, 0, 4])

In [225]:
shuffle = np.vectorize(np.random.permutation, signature='(n)->(n)')

In [232]:
z = shuffle(y.T).T
z

array([[1, 4, 3, 0, 3],
       [3, 3, 0, 4, 1],
       [4, 2, 4, 1, 4],
       [0, 1, 1, 3, 2],
       [2, 0, 2, 2, 0]])

In [238]:
seats = np.zeros((5,5))
seats[0,:] = np.random.randint(5, size = 5)

In [239]:
seats

array([[1., 4., 3., 4., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [230]:
def airplane_sim2(sims=5, n=5):
    lggas = 0 # last guy gets assigned seat
    seats = np.zeros((n,sims))
    seats[0,:] = np.random.randint(5, size=5)
    for p in range(n):
        

array([[1, 1, 2, 3, 2],
       [0, 0, 4, 2, 3],
       [4, 3, 1, 4, 0],
       [3, 2, 0, 0, 1],
       [2, 4, 3, 1, 4]])

In [ ]:
airplane_sim2()

In [156]:
hats = np.arange(100)
np.random.shuffle(hats)

In [132]:
hats

array([ 4, 13, 22,  2, 61, 93, 38, 79, 52,  7, 39, 35, 57, 71, 15, 32, 70,
       43, 31, 92, 96, 68, 48,  0, 49, 51, 17, 53, 84, 50, 54, 14, 72, 91,
       33, 90, 75,  6, 12, 55, 44, 74, 46, 30,  1, 20, 85,  8, 42, 63, 27,
       95, 65, 86, 36, 37, 59, 83, 29, 67, 81, 87, 78, 41, 10, 11, 58, 99,
        9, 25, 23,  5, 18, 56, 28, 94, 97, 62, 77, 69, 24, 73, 80, 21, 89,
       88,  3, 66, 16, 76, 47, 82, 64, 19, 60, 98, 45, 26, 34, 40])

In [159]:
hats = np.arange(100)
np.random.shuffle(hats)
any(np.equal(hats, np.arange(100)))

True

In [177]:
def hats_sim(sims = 100, n = 10):
    num = 0
    for i in range(sims):
        hats=np.arange(n)
        np.random.shuffle(hats)
        num += any(np.equal(hats, np.arange(n)))
    return 1 - num/sims

In [762]:
n_passengers = 1000
n_planes = 100
x = np.arange(n_passengers)
y = np.repeat(x, n_planes, axis = 0)
y = y.reshape((n_passengers, n_planes))
y[0,:] = np.random.randint(n_passengers, size=n_planes)
for p in range(1, n_passengers):
    q = np.where(y[:p] == p)[1]
    y[p,q] = np.random.randint(p+1, n_passengers+1, size=len(q)) % n_passengers
lggas = y[n_passengers - 1,:].astype(bool).sum()
print(np.sum(y, axis=0))
print(lggas)


[499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500
 499500 499500 499500 499500 499500 499500 499500 499500 499500 499500]
49


In [694]:
airplane_sim2(100,1000)

0.503